version: '3.8'

services:
  api:
    build: .
    ports:
      - "5005:5005"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/taskdb
      - PORT=5005
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: